### PR TITLE
Added ability to register additional interface implementations

### PR DESCRIPTION
**Pull request by BlackGad**
# Description

Internal DI discovery MediatR mechanism is black box for others. This PR adds ability to use same rules for additional custom types. Feature can be useful for validators and other behavior extensions.

# Example

[FluentValidation](https://fluentvalidation.net/) integration into pipeline without additional manual validators registration.

## Behavior extension

Pre handle validation behavior

```CSharp
public class RequestValidationBehavior<TRequest, TResponse> : IPipelineBehavior<TRequest, TResponse>
{
    private readonly IEnumerable<IValidator<TRequest>> _validators;

    public RequestValidationBehavior(IEnumerable<IValidator<TRequest>> validators)
    {
        _validators = validators;
    }

    public async Task<TResponse> Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate<TResponse> next)
    {
        foreach (var validator in _validators)
        {
            await validator.ValidateAndThrowAsync(request, cancellationToken);
        }
        
        return await next();
    }
}
```

## DI registration

```CSharp
var provider = new ServiceCollection()
                .AddMediatR(config =>
                {
                    config.AdditionalClasses.Add(new TypeRegistration(typeof(IValidator<>)));
                }, typeof(Ping));
                .AddTransient(typeof(IPipelineBehavior<,>), typeof(RequestValidationBehavior<,>));
                .BuildServiceProvider();
```

## Handler, Request and Validator implementation

```CSharp
public class CustomRequest : IRequest<bool>
{
    public string Title { get; set; }
}

public class CustomRequestValidator : AbstractValidator<CustomRequest>
{
    public CustomRequestValidator()
    {
        RuleFor(x => x.Title)
            .NotEmpty();
    }
}

public class CustomRequestHandler : IRequestHandler<CustomRequest, bool>
{
    public async Task<bool> Handle(CustomRequest request, CancellationToken cancellationToken)
    {
        await Task.Delay(0, cancellationToken);
        return true;
    }
}
```

## Usage

```CSharp
var mediator = provider.GetRequiredService<IMediator>();
var result = await mediator.Send(new CustomRequest());
```

### CODE REVIEW

**Comment by jbogard** [comment]
The internal registration code is pulled from a 3rd-party container (StructureMap). If you want that registration behavior, you should Scrutor or a different container. I don't really want to expose/support registration code that I """borrowed""" from somewhere else.

**Comment by BlackGad** [comment]
> The internal registration code is pulled from a 3rd-party container (StructureMap). If you want that registration behavior, you should Scrutor or a different container. I don't really want to expose/support registration code that I """borrowed""" from somewhere else.

But in fact everyone is used MediatR :) So source of this code is irrelevant now. You became too famous). Please, add ability to use custom interfaces. I have additional ideas for upgrade but this one is obvious for my projects.

**Comment by BlackGad** [comment]
Any chance to be merged?

**Comment by jbogard** [comment]
No, I really don't want to have to support this. I understand it's valuable but I don't want to get GitHub issues when this registration won't work for some other library for whatever reason.

**Pull request closed without merging**
